
about:
  title: 关于我
  description: 个人博客
  name: 小余
  age: 2001
  location: 重庆
  experience: 软件工程硕士在读
  email: yy381106114@163.com
  social_media:
    github: https://github.com/jiangbianxiaoY/blog-vue.git
    
  interests:
    - C++开发
    - Nodejs开发
    - 历史
    - 社会科学
    - 机器学习

  search:
    - 机器学习
    - 极化SAR
    - 图像识别
    - 后端开发
