[mongo]
    host = "127.0.0.1:27017"
    user = "jiangbianxiaoyu"
    passwd = "yu3114654955"
    maxpoolsize = 10
    contimeout  = "5000"
    maxconidle = "5000"
    database = "blog_dev"

[cookie]
    #host = "47.110.236.84"
    #本地启动请设置host为本地
    host = "localhost"
    alive = 86400

[location]
    timezone = "Asia/Shanghai"

[redis]
    host = "127.0.0.1:6379"
    idlecons = 16
    poolsize = 1024
    idletimeout = 300
    passwd = "123456"
    db = 1
